config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get "about" => "pages#about", as: :about

  get "blog" => "pages#blog", as: :blog

  get "artist" => "pages#artist", as: :artist

  get "test" => "pages#test", as: :test



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def blog
  end

  def artist
  end

  def test
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Wm2b</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <div class="main-page-content <%= controller.controller_name %>">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:listen, "active") %>
<% provide(:title, "Listen") %>

<!DOCTYPE html>
<html lang="en">
  <head>

  </head>

  <!--<body>
     <div class="jumbotron">
      <div class="container">
        <h1>Wm2b Music</h1>
        <p>All songs are property of artist</p>
        
      </div>
    </div>-->
    <div id="bg-fade-carousel" class="carousel slide carousel-fade" data-ride="carousel">
<!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="slide1"></div>
        </div>
        <div class="item">
            <div class="slide2"></div>
        </div>
        <div class="item">
            <div class="slide3"></div>
        </div>
    </div><!-- .carousel-inner --> 
    <div class="container carousel-overlay party text-left">
        
   
      <h1>Wm2b Listen</h1>
        <h3>All Songs are property of artist.</h3>
        </p>
      </div>
    </div>
    </div>

</div><!-- .carousel --> 
<!--end bg-carousel-->
 <!-- Core JavaScript -->
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</body>
 <%#-------------------------------------------------Facebook button group-----------------------------%>
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=412994489042277";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=412994489042277";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<%#-------------------------------------------------Facebook button group-------------------------------%>

<div class="col-md-8 col-md-offset-2">
<div class="fb-login-button" data-max-rows="1" data-size="small" data-show-faces="true" data-auto-logout-link="false"></div>

    <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div><hr>

<center><h4><em>Check back soon as most of these artists are working on new material.  Coming soon is a streaming music player, but for now enjoy these videos.</em>  </h4></center><hr>
<%#---------------------------------------------------------AnchAff1 -----------------------------------%>
<center><h2>Anchors Affliction</h2></center><br>
<center><h3>Prevail</h3></center><br>
<!-- 16:9 aspect ratio -->
 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/FpXnC_6yGHw"></iframe>
 </div>
<br><hr><br>
<%#---------------------------------------------------------AnchAff2 ------------------------------------%>
<center><h2>Anchors Affliction</h2></center><br>
<center><h3>Lost Cause</h3></center><br>
<!-- 16:9 aspect ratio -->
 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/mC1dvTtVHps"></iframe>
 </div>
<br><hr><br>
<%#---------------------------------------------------------Ancient Elk-----------------------------------%>
<center><h2>Ancient Elk</h2></center><br>
<center><h3>The Quilt</h3></center><br>
<!-- 16:9 aspect ratio -->
 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/8Rt_LAklWEA"></iframe>
 </div>
<br><hr><br>

<%#---------------------------------------------------------GlasTake1--------------------------------------%>

<center><h2>Glass Apparatus</h2></center><br>
<center><h3>Take Her Away</h3></center><br>
<!-- 16:9 aspect ratio -->
 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/YxLtlDsJgbs"></iframe>
 </div>
<br><hr><br>
<%#---------------------------------------------------------GlasAmj2--------------------------------------%>

<center><h2>Glass Apparatus</h2></center><br>
<center><h3>Amerijuanica</h3></center><br>
<!-- 16:9 aspect ratio -->
 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/vUUptWLXnA4"></iframe>
 </div>
<br><hr><br>
<%#---------------------------------------------------------GlasAmj2--------------------------------------%>

<center><h2>Glass Apparatus</h2></center><br>
<center><h3>We Will Never Know</h3></center><br>
<!-- 16:9 aspect ratio -->
 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/n4LLPCy5AUI?list=PLNzsH4AXWIJOF4yAo9A27LIrIm2K6bsja"></iframe>
 </div>
<br><hr><br>

<%#---------------------------------------------------------JWeeks Because of you -------------------------%>
<center><h2>Jared Weeks</h2></center><br>
<center><h3>Because of You</h3></center><br>
<!-- 16:9 aspect ratio -->

 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/2qgWWjTeCEc"></iframe>
 </div>

<br><hr><br>
<%#---------------------------------------------------------JWeeks Because of you -------------------------%>
<center><h2>Jared Weeks</h2></center><br>
<center><h3>One Goodbye</h3></center><br>
<!-- 16:9 aspect ratio -->

 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/0Omx_lNqzjk"></iframe>
 </div>

<br><hr><br>
<%#---------------------------------------------------------NovaInMotiont Partners in crime ---------------%>
<center><h2>Nova In Motion</h2></center><br>
<center><h3>Partners In Crime</h3></center><br>
<!-- 16:9 aspect ratio -->
 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/svvLdzB98oo"></iframe>
 </div>
<br><hr><br>
<%#---------------------------------------------------------RHett -------------------------%>
<center><h2>Rhett Uhland</h2></center><br>
<center><h3>Music To Be Made</h3></center><br>
<!-- 16:9 aspect ratio -->
 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/iiXUsMtPAao"></iframe>
 </div>
<br><hr><br>
<%#---------------------------------------------------------Silent Redemption-------------------------%>
<center><h2>Silent Redemption</h2></center><br>
<center><h3>Fury and Fight</h3></center><br>
<!-- 16:9 aspect ratio -->
 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/NfDlfqyeIqQ"></iframe>
 </div>
<br><hr><br>
<%#---------------------------------------------------------Silent Redemption-------------------------%>
<center><h2>Silent Redemption</h2></center><br>
<center><h3>Caught</h3></center><br>
<!-- 16:9 aspect ratio -->
 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/r942OpiWlu0"></iframe>
 </div>
<br><hr><br>
<%#---------------------------------------------------------T R I P C --------------------------------------%>

<center><h2>TRIPC</h2></center><br>
<center><h3>Leelaand</h3></center><br>
<!-- 16:9 aspect ratio -->
 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ni_tttXuqW0"></iframe>
 </div>
<br><hr><br>

<%#---------------------------------------------------------T R I P C ---------------------------------------%>

<center><h2>TRIPC</h2></center><br>
<center><h3>Chickenlooper</h3></center><br>
<!-- 16:9 aspect ratio -->
 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/3VeTMtu5Kgc"></iframe>
 </div>
<br><hr><br>

<%#---------------------------------------------------------T R I P C --------------------------------------%>

<center><h2>TRIPC</h2></center><br>
<center><h3>Gyotp</h3></center><br>
<!-- 16:9 aspect ratio -->
 <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ZldHSLCCwkE"></iframe>
 </div>
<br><hr><br>
</div>
</body>

</html>
<%#---------- TEMPLATE ----------%>
<%#---------- TEMPLATE ----------%>
<%#---------- TEMPLATE ----------%>

app/views/pages/artist.html.erb
<% provide(:artist, "active") %>
<% provide(:title, "Artist") %>

<!DOCTYPE html>
<html lang="en">
  <head>

  </head>
<body>
     <!--<div class="jumbotron">
      <div class="container">
        <h1>Wm2b Music</h1>
        <p>Artist Information (A-Z)</p>
        
      </div>
    </div>-->
<div id="bg-fade-carousel" class="carousel slide carousel-fade" data-ride="carousel">
<!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="slide1"></div>
        </div>
        <div class="item">
            <div class="slide2"></div>
        </div>
        <div class="item">
            <div class="slide3"></div>
        </div>
    </div><!-- .carousel-inner --> 
    <div class="container carousel-overlay party text-left">
        
   
      <h1>Wm2b Artist</h1>
        <h3>Featured artists and official links</h3>
        </p>
      </div>
    </div>
    </div>

</div><!-- .carousel --> 
<!--end bg-carousel-->
 <!-- Core JavaScript -->
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</body>
<br>
<br>
<br>
 <%#-------------------------------------------------Facebook button group-----------%>
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=412994489042277";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=412994489042277";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<%#-------------------------------------------------Facebook button group-----------%>
<div class="container">
<div class="fb-login-button" data-max-rows="1" data-size="small" data-show-faces="true" data-auto-logout-link="false"></div>

    <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div><hr></div>
	<%# ANchors 1 ------------------------------------------------------------------%>
    <div class="jumbotron aa">
      <div class="container">
        <h1>Anchors Affliction</h1>
        <p>Denver, Colorado</p>
        <%= link_to 'AnchorsAffliction.com', 'https://www.anchorsaffliction.com/' %> | 
        <%= link_to 'Facebook', 'https://www.facebook.com/Anchorsaffliction/' %> | 
        <%= link_to 'Twitter', 'https://twitter.com/therealanchors' %> | 
        <%= link_to 'YouTube', 'https://www.youtube.com/channel/UCJM3D65Bq-sYi8wUnHCbZzw' %>
	<div class="row">

        <div class="col-xs-10 col-md-8">
		<h4>Anchors Affliction is an American metalcore band from Denver, Colorado that was established in 2015 by drummer Dalton Akerfelds and bassist Jared Pattynama. The band’s sound comes from a mix of hardcore, metalcore, and post-hardcore influences.  The band's current line up consists of Tyler Hill and Joshua Everetts sharing vocal duties, Kevin Harrison and Jace Hill on guitars, bassist Jared Pattynama and drummer Dalton Akerfelds. </h4>
		</div>
		</div>
        </div>
    </div>

<br>
<br>
<br>
<%# sd  7 ------------------------------------------------------------------%>
    <div class="jumbotron ae">
      <div class="container">
        <h1>Ancient Elk</h1>
        <p>Denver, Colorado</p>
        <%= link_to 'Ancient Elk Bandcamp', 'http://ancientelk.bandcamp.com/releases' %> | 
        <%= link_to 'Facebook', 'https://www.facebook.com/ancientelk' %> | 
        <%= link_to 'Email', 'mailto:ancientelkband@gmail.com' %> | 
        <%= link_to 'YouTube', 'https://www.youtube.com/channel/UCtuNFFwnENSMI_TyG61jnDg' %>
    <div class="row">

        <div class="col-xs-10 col-md-8">
        <h4>Ancient Elk represents a synthesis of various sounds that have informed a wide spectrum of musical styles that have been running through Denver. Reconciling seemingly incompatible ideas from its members differing backgrounds, the band threads together Americana, psychedelic rock, jazz and experimental music in an original way that is also incredibly accessible. They released self-titled cassette EP in July 2014. -Tom Murphy

</h4>
        </div>
        </div>
        </div>
    </div>

<br>
<br>
<br>
	<%# Dieverse 2 ------------------------------------------------------------------%>
    <div class="jumbotron dd">
      <div class="container">
        <h1>DieVerse Disorder</h1>
        <p>Lamar, Colorado</p>
        
        <%= link_to 'Facebook', 'https://www.facebook.com/dieversedisorderband/' %> 
        
	<div class="row">

        <div class="col-xs-10 col-md-8">
		<h4>DieVerse Disorder Is a metalcore band from Lamar, Colorado.  Formed in 2016, it included brothers Joe and Henry Lundy (formerly of the bands Reckless High and Little Wing) and singer Adrian Licano (formerly of Seeking Chaos).  They later added drummer Nestor Castro.  They're first single "Scream" shows what these boys are all about; tight melodic riffs, a driving rhythm section, and aggressive vocals.  They are currently working on new material, check out their facebook page and soundcloud page.  </h4>
		</div>
		</div>
        </div>
    </div>


<br>
<br>
<br>
	<%# Glass 3 ------------------------------------------------------------------%>
   <div class="jumbotron ga">
      <div class="container">
        <h1>Glass Apparatus</h1>
        <p>Eads, Colorado</p>
        <%= link_to 'GlassApparatus.net', 'http://www.glassapparatus.net' %> | 
        <%= link_to 'Facebook', 'https://www.facebook.com/glass.apparatus' %> | 
        <%= link_to 'Twitter', 'https://twitter.com/Glass_Apparatus' %> | 
        <%= link_to 'YouTube', 'https://www.youtube.com/user/GlassApparatus' %>
	<div class="row">

        <div class="col-xs-10 col-md-8">
		<h4>Meet Glass Apparatus.  Formed in 2012 by brothers Jeremy and Josh Brown(bass and drums respectively), and a lifelong friend John Barton (guitar).  Lastly, they added singer Jamie Crockett, and they recorded a debut double album "The Glass House Sessions Vol 1,2".  Other former notable members include Cory Crow (guitar/bass), Justin Crain (bass), and Darin Epper (drums).</h4>
		</div>
		</div>
        </div>
    </div>


<br>
<br>
<br>
	<%# Weeks 4 ------------------------------------------------------------------%>
    <div class="jumbotron jw">
      <div class="container">
        <h1>Jared Weeks</h1>
        <p>Kit Carson, Colorado</p>
        <%= link_to 'Twitter', 'https://twitter.com/jaredweeks4181' %> | 
        <%= link_to 'YouTube', 'https://www.youtube.com/channel/UCA0d8sr8NCRioxMIR6KWBrg' %>
        <div class="row">

        <div class="col-xs-10 col-md-8">
        <h4>Jared Weeks is a 16 year old singer/songwriter from Kit Carson, Colorado.  His music consists of acoustic and electric elements that come together for a modern sound.  </h4>
      </div>
    </div>
</div>
</div>

<br>
<br>
<br>
<%# Nova 5 ------------------------------------------------------------------%>
    <div class="jumbotron nm">
      <div class="container">
        <h1>Nova In Motion</h1>
        <p>La Junta, Colorado</p>
         
        <%= link_to 'Facebook', 'https://www.facebook.com/novainmotionband/' %> | 
        <%= link_to 'Twitter', 'https://twitter.com/NovaInMotion1' %> | 
        <%= link_to 'YouTube', 'https://www.youtube.com/user/HDnumba1pLaYa' %>
	<div class="row">

        <div class="col-xs-10 col-md-8">
		<h4>Nova In Motion is a band from Southeast Colorado trying to come from nothing to something by creating innovative sounds and challenging their musical skills, so that in the end, people can connect to the music on a deep personal level.
        <br>
        "Their music speaks for themselves."
         </h4>
		</div>
		</div>
        </div>
    </div>

<br>
<br>
<br>
<%# Rhett 6 ------------------------------------------------------------------%>
    <div class="jumbotron ru">
      <div class="container">
        <h1>Rhett Uhland</h1>
        <p>Eads, Colorado</p>
         
        <%= link_to 'Facebook', 'https://www.facebook.com/rfumusic/' %> | 
        <%= link_to 'Twitter', 'https://twitter.com/therealanchors' %> | 
        <%= link_to 'YouTube', 'https://www.youtube.com/channel/UCYVb__RY5B-UMgXbSPbu6bA' %>
	<div class="row">

        <div class="col-xs-10 col-md-8">
		<h4>Rhett Uhland is a 16 year old singer/singwriter from Eads, Colorado.  Rhett has a powerful, recognizable voice that can carry a song all by itself.  Well known to the town for his memorable performaces, Rhett is a hopefull young country music artist. </h4>
		</div>
		</div>
        </div>
    </div>

<br>
<br>
<br>
<%# sd  7 ------------------------------------------------------------------%>
    <div class="jumbotron sd">
      <div class="container">
        <h1>Silent Redemption</h1>
        <p>Dubuque, Iowa</p>
        <%= link_to 'SilentRedemption.rocks', 'http://www.silentredemption.rocks' %> | 
        <%= link_to 'Facebook', 'https://www.facebook.com/SilentRedemption/?ref=br_rs' %> | 
        <%= link_to 'Twitter', 'https://twitter.com/therealanchors' %> | 
        <%= link_to 'YouTube', 'https://www.youtube.com/user/SilentRedem' %>
	<div class="row">

        <div class="col-xs-10 col-md-8">
		<h4>From the Iowa corn fields comes a band that is changing the face of music!  Silent Redemption is made up of James Robinson (vocals and guitar), Robbie Bauer (bass), and William Fish (drums).
</h4>
		</div>
		</div>
        </div>
    </div>

<br>
<br>
<br>
<%# ccc 8------------------------------------------------------------------%>
    <div class="jumbotron ccc">
      <div class="container">
        <h1>TRIPC</h1>
        <p>Eads, Colorado</p>
        
        <%= link_to 'YouTube', 'https://www.youtube.com/cccmusicality' %>
	<div class="row">

        <div class="col-xs-10 col-md-8">
		<h4>Electronic music from Wm2b's creator.  Highly influenced by artist such as Ahpex Twin, Boards Of Canada, Autechre, Download and Luke Vibert.  </h4>
		</div>
		</div>
        </div>
    </div>

<br>
<br>
<br>
</body>
</html>

app/views/pages/home.html.erb
<% provide(:home, "active") %>
<% provide(:title, "Home") %>

<!DOCTYPE html>
<html lang="en">
  <head>
  </head>

  <body>
<%#-------------------------------------------------Facebook button group-----------%>
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=412994489042277";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=412994489042277";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<%#-------------------------------------------------Facebook button group-----------%>

<!-- Main jumbotron for a primary marketing message or call to action 
    <div class="jumbotron">
      <div class="container">
        <h1>Wm2b Music</h1>
        <p>Featuring New Colorado Music</p>
        
      </div>
    </div>
Main jumbotron for a primary marketing message or call to action -->

<div id="bg-fade-carousel" class="carousel slide carousel-fade" data-ride="carousel">
<!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="slide1"></div>
        </div>
        <div class="item">
            <div class="slide2"></div>
        </div>
        <div class="item">
            <div class="slide3"></div>
        </div>
    </div><!-- .carousel-inner --> 
    <div class="container carousel-overlay party text-left">
        
   
      <h1>Wm2b Music</h1>
        <h3>Featuring New Colorado Music</h3>
        </p>
      </div>
    </div>
    </div>

</div><!-- .carousel --> 
<!--end bg-carousel-->
 <!-- Core JavaScript -->
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</body>
<%#---------------------------------------------------------------Button Container---------%>
    <div class="container">

      <div class="fb-login-button" data-max-rows="1" data-size="small" data-show-faces="true" data-auto-logout-link="false"></div>

    <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>

<hr>
      <!-- Example row of columns -->
      <div class="row">
          <div class="col-sm-4">
          <h2>Listen   <span class="glyphicon glyphicon-volume-up" aria-hidden="true"></span></h2>
          <p>The goods.</p>
          <p>Here you can listen to songs from some great acts.  There is a little something for everybody.</p>
          <p><a class="btn btn-default" href="about" role="button"><span class="glyphicon glyphicon-volume-up" aria-hidden="true"></span> &raquo; </a></p>
       </div>


         <div class="col-sm-4">
          <h2>Artist   <span class="glyphicon glyphicon-sunglasses" aria-hidden="true"></span></h2>
          <p>Find out more about the artists and their music.</p>
          <p><a class="btn btn-default" href="artist" role="button"><span class="glyphicon glyphicon-sunglasses" aria-hidden="true"></span> &raquo;</a></p>
        </div>

        <div class="col-sm-4">
          <h2>Blog    <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span></h2>
          <p>Visit the Blog to find recent news and happenings.  Updated regularly.  </p>
          <p><a class="btn btn-default" href="blog" role="button"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> &raquo;</a></h1>
        </div>
        </div>
<%#---------------------------------------------------------------Button Container End---------%>
  <hr>
    <footer>
        <small><p>&copy; 2017 Digital_Bath Developement</p></small>
    </footer>
    </div> <!-- /container -->

</body>
</html>

app/views/pages/test.html.erb
<div id="bg-fade-carousel" class="carousel slide carousel-fade" data-ride="carousel">
<!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="slide1"></div>
        </div>
        <div class="item">
            <div class="slide2"></div>
        </div>
        <div class="item">
            <div class="slide3"></div>
        </div>
    </div><!-- .carousel-inner --> 
    <div class="container carousel-overlay party text-left">
        
   
      <h1>Wm2b Music</h1>
        <h3>Featuring New Colorado Music</h3>
        </p>
      </div>
    </div>
    </div>

</div><!-- .carousel --> 
<!--end bg-carousel-->
 <!-- Core JavaScript -->
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</body>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top"role ="navigation">
  <div class="container ">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">W M 2 B</a>
      
    
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
         
    

        <li class="<%= yield(:home)%>"><%= link_to "Home", root_path %></li>
        <li class="<%= yield(:listen)%>"><%= link_to "Listen", about_path %></li>
        <li class="<%= yield(:artist)%>"><%= link_to "Artist", artist_path %></li>
        <li class="<%= yield(:blog)%>"><%= link_to "Blog", blog_path %></li>
        
        
        
        

       


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>